services:
  vue-nginx:
    image: ghcr.io/nrf24l01/vue_citate_gen/vue-nginx:latest
    network_mode: host
    restart: unless-stopped

  watchtower-quoter-frontend:
    image: containrrr/watchtower
    container_name: watchtower-quoter-frontend
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
