name: Build and Deploy Vue.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Собираем Vue.js
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')  # Приводим к нижнему регистру
          docker build -t ghcr.io/$REPO_NAME/vue-builder -f Dockerfile.build .
          docker create --name extract ghcr.io/$REPO_NAME/vue-builder
          docker cp extract:/app/dist ./dist


      - name: Собираем финальный Nginx-образ
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/vue-nginx .

      - name: Пушим образ в GHCR
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')  # Нижний регистр
          docker push ghcr.io/$REPO_NAME/vue-nginx

